### ISSUE TITLE
reference to 'Stream' is ambiguous error

### ISSUE THREAD

**Issue by yari0757** [khoih-prog/WiFiManager_Portenta_H7_Lite#2]
### Describe the bug

HI
I am trying to use this library but when include any of this library, i faced with this error:
**error: reference to 'Stream' is ambiguous.**
libraries:
#include "Arduino_BHY2Host.h"
#include <ArduinoJson.h>
#include <PubSubClient.h>
  

```
Arduino IDE version: 1.8.19
Portenta h7 lite latest frimware
OS: Ubuntu 20.04 LTS

**Comment by khoih-prog** [comment]
Hi @yari0757 

What a **nonsense** you post. If you add a new library and get compile error, that must be the issue of the newly-added library.

Anyway, I tested and compile OK, with the inclusion of those 3 libraries

If you continue **lazily posting this kind of nonsense again**, you'll be blocked from accessing these libraries to reduce wasting time of other people.

---



![Selection_175](https://user-images.githubusercontent.com/57012152/198923542-5e72e950-8ada-457d-bdff-8f79bac2a12b.png)

**Comment by yari0757** [comment]
You can't threaten people that easily.  It is my absolute right to ask my question and this is what this place was created for.  The quality of asking questions is completely related to the level of expertise of people in that field, and I am currently a junior in your field of work.  I will report your threatening behavior to GitHub.
